# Introduction to NumPy

---

##  Theory

NumPy (Numerical Python) is a powerful open-source Python library used for numerical computing.  
It provides support for:
- Multidimensional arrays (ndarray)
- Mathematical operations on arrays
- Linear algebra, Fourier transforms, random number generation

NumPy is faster than regular Python lists because it uses optimized **C libraries** internally.  
It is the foundation for many data science and machine learning libraries such as **Pandas, TensorFlow, SciPy, and Scikit-learn**.

---


##  Applications

- Handling large multidimensional arrays and matrices.
- Performing mathematical and statistical operations efficiently.
- Data preprocessing in Machine Learning.
- Basis for scientific computing libraries.
- Used in image processing, signal processing, and simulations.
- Vectorization (eliminating loops, improving performance).


## 3. List of Functions and Their Usage

Some important NumPy functions:

| Function | Usage |
|----------|--------|
| `np.array()` | Create an array |
| `np.arange(start, stop, step)` | Create array with range of values |
| `np.zeros((m,n))` | Create array filled with zeros |
| `np.ones((m,n))` | Create array filled with ones |
| `np.eye(n)` | Identity matrix |
| `np.linspace(start, stop, num)` | Create evenly spaced numbers |
| `np.random.rand(m,n)` | Random numbers between 0 and 1 |
| `np.shape` | Get dimensions of array |
| `np.reshape()` | Reshape array |
| `np.sum(), np.mean(), np.std()` | Aggregation functions |
| `np.min(), np.max(), np.argmin(), np.argmax()` | Min/Max values & indices |
| `np.dot(), np.matmul()` | Matrix multiplication |
| `np.transpose()` | Transpose of matrix |
| `np.sort()` | Sorting array |

---


##Practice Section-1


In [ ]:
import numpy as np
array1 = np.array([1,2,3,4])
print(array1)
array2 = np.array([1,2,3,4]),([5,6,7,8])
print(array2)

zero = np.zeros((4,4))
print("Zero array: ", zero)

one = np.ones((4,4))
print("Ones array: ", one)

identity = np.eye(4)
print(identity)

line_space = np.linspace(1,3,5)
print(line_space)

randnum = np.random.rand(2,3)
print(randnum)

randnumber = (np.random.rand(2,3)*10).astype(int)
print(randnumber)

#dimentions of array1 & array2
array1_shape = np.shape(array1)
array2_shape = np.shape(array2)
print(array1_shape)
print(array2_shape)

print(np.shape(array1))
print(np.shape(array2))

arr = np.arange(2,10).reshape(4,2)
print(arr)

[1 2 3 4]
(array([1, 2, 3, 4]), [5, 6, 7, 8])
Zero array:  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array:  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[1.  1.5 2.  2.5 3. ]
[[0.37494518 0.22546804 0.72783477]
 [0.90496205 0.25930209 0.58495134]]
[[7 3 8]
 [7 1 7]]
(4,)
(2, 4)
(4,)
(2, 4)
[[2 3]
 [4 5]
 [6 7]
 [8 9]]


##Practice Section-2

In [ ]:
import numpy as np
arr1 = np.array([[1,3,5,7],[2,4,6,8]])
arr2 = np.array([[2,5,8,3],[1,2,4,6]])

print(arr1)
print(arr2)

#1d array
array1 = np.array([1,2,3,4])
print(array1)

#2d array
array1 = np.array ([[1,3,5,7],[2,4,6,8]])
print(array1)

#3d array
array1 =np.array([[[1,2,3],[2,3,4],[4,5,6]]])
print(array1)

zero_arr = np.zeros((3,4))
print(zero_arr)

ones_arr = np.ones((4,5))
print(ones_arr)

identity_arr = np.eye(4)
print(identity_arr)

arrange_arr = np.arange(1,20,2) #Step size
print(arrange_arr)
print(np.arange(2,30,2))

line_space_arr = np.linspace(1,10,5)#Number of values
print(line_space_arr)
print(np.linspace(1,5,5))

randnum_arr = np.random.rand(3,3)
print(randnum_arr)

arr1_shape = np.shape(arr1)
print(arr1_shape)
print(np.shape(arr2))

arr2_reshape = arr2.reshape(4,2)
print(arr2_reshape)
print(np.shape(arr2_reshape))

print(arr2)
print(np.shape(arr2))

range_arr = np.arange(1,9)
print(range_arr)
print(np.shape(range_arr))

print(range_arr.reshape(2,4))
print(np.shape(range_arr))

[[1 3 5 7]
 [2 4 6 8]]
[[2 5 8 3]
 [1 2 4 6]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[ 1  3  5  7  9 11 13 15 17 19]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28]
[ 1.    3.25  5.5   7.75 10.  ]
[1. 2. 3. 4. 5.]
[[0.6290404  0.85625767 0.84881166]
 [0.65453897 0.85064491 0.66091697]
 [0.4039454  0.87344535 0.48331936]]
(2, 4)
(2, 4)
[[2 5]
 [8 3]
 [1 2]
 [4 6]]
(4, 2)
[[2 5 8 3]
 [1 2 4 6]]
(2, 4)
[1 2 3 4 5 6 7 8]
(8,)
[[1 2 3 4]
 [5 6 7 8]]
(8,)


##Practice Section-3

In [ ]:
new_arr1 = np.array([[2,5,8],[3,4,7]])
new_arr2 = np.array([[1,2,3],[4,5,6]])
print(new_arr1)
print(new_arr2)

sum = np.sum(new_arr1)
print(sum)

addition = np.add(new_arr1,new_arr2)
print(addition)

subtract = np.subtract(new_arr1,new_arr2)
print(subtract)
print(np.multiply(new_arr1,new_arr2))
print(np.divide(new_arr1,new_arr2))
print(np.sqrt(new_arr1))
print(np.sqrt(new_arr2))

Mean = np.mean(new_arr1)
print(Mean)

Standard_Dev = np.std(new_arr1)
print(Standard_Dev)

Variance = np.var(new_arr1)
print(Variance)

Min = np.min(new_arr1)
print(Min)

Max = np.max(new_arr1)
print(Max)

Arg_min = np.argmin(new_arr1)
print(Arg_min)

Arg_max = np.argmax(new_arr1)
print(Arg_max)

X = np.array(([3,4],[5,6]))
Y = np.array(([8,9],[6,7]))
Dot_product = np.dot(X,Y)
print(Dot_product)

print(np.matmul(X,Y))

Arr = new_arr1.reshape(3,2)
print(new_arr1)
print(Arr)
print(Arr.T)

Array = np.array([1,8,3,5,2,6,7])
sorted_arr = np.sort(Array)
print(sorted_arr)



[[2 5 8]
 [3 4 7]]
[[1 2 3]
 [4 5 6]]
29
[[ 3  7 11]
 [ 7  9 13]]
[[ 1  3  5]
 [-1 -1  1]]
[[ 2 10 24]
 [12 20 42]]
[[2.         2.5        2.66666667]
 [0.75       0.8        1.16666667]]
[[1.41421356 2.23606798 2.82842712]
 [1.73205081 2.         2.64575131]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
4.833333333333333
2.1147629234082532
4.472222222222222
2
8
0
2
[[48 55]
 [76 87]]
[[48 55]
 [76 87]]
[[2 5 8]
 [3 4 7]]
[[2 5]
 [8 3]
 [4 7]]
[[2 8 4]
 [5 3 7]]
[1 2 3 5 6 7 8]


##NumPy Mini Revision

In [ ]:
# Importing NumPy
import numpy as np

# Creating Arrays
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([[1, 2, 3], [4, 5, 6],[9,10,11],[11,12,13]])

print("1D Array:", arr1)
print("2D Array:\n", arr2)

# Array with specific values
zeros = np.zeros((3,4))
ones = np.ones((2,3))
identity = np.eye(5)

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Identity Matrix:\n", identity)

# Range and linspace
arange_arr = np.arange(1, 45, 2)
linspace_arr = np.linspace(1, 2, 4)

print("Arange:", arange_arr)
print("Linspace:", linspace_arr)

# Random numbers
rand_arr = np.random.rand(2,3)
print("Random Array:\n", rand_arr)
otp =( (rand_arr*1000000)).astype(int)
print("Random Array:\n", otp)


# Example 1: Reshape and Transpose
matrix = np.arange(1, 13).reshape(4,3)
print("Matrix:\n", matrix)
print("Transpose:\n", matrix.T)

# Example 2: Mathematical operations
arr = np.array([10, 20, 30, 40])
print("Original Array:", arr)
print("Array + 5:", arr - 5)
print("Array squared:", arr ** 2)

# Example 3: Aggregate Functions
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))

# Example 4: Matrix multiplication
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print("Matrix Multiplication:\n", np.dot(A,B))

# Example 5: Sorting
unsorted = np.array([3,1,4,1,5,9])
print("Sorted Array:", np.sort(unsorted))


1D Array: [1 2 3 4 5 6]
2D Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 9 10 11]
 [11 12 13]]
Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Arange: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43]
Linspace: [1.         1.33333333 1.66666667 2.        ]
Random Array:
 [[0.43663429 0.70460498 0.20525033]
 [0.66607141 0.97230373 0.80591331]]
Random Array:
 [[436634 704604 205250]
 [666071 972303 805913]]
Matrix:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Transpose:
 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
Original Array: [10 20 30 40]
Array + 5: [ 5 15 25 35]
Array squared: [ 100  400  900 1600]
Sum: 100
Mean: 25.0
Standard Deviation: 11.180339887498949
Matrix Multiplication:
 [[19 22]
 [43 50]]
Sorted Array: [1 1 3 4 5 9]


In [ ]:
#MORNING TASK
#1
import numpy as np
Array1 = np.arange(1,20)
print(Array1)

#2
Array2 = np.zeros(10)
print(Array2)
print(np.shape(Array2))
print(Array2.reshape(5,2))

#3
Array3 = np.arange(2,21,2)
print(Array3)

#4
Array4 = np.array([[1,3,2,4],[2,3,4,5]])
print(Array4)
print(np.shape(Array4))
print(Array4.size)
print(Array4.dtype)
print(Array4 *2)

#5
Array5 = np.eye(4)
print(np.sum(Array5))
print(np.mean(Array5))
print(np.min(Array5))
print(np.max(Array5))
print(np.std(Array5))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(10,)
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[ 2  4  6  8 10 12 14 16 18 20]
[[1 3 2 4]
 [2 3 4 5]]
(2, 4)
8
int64
[[ 2  6  4  8]
 [ 4  6  8 10]]
4.0
0.25
0.0
1.0
0.4330127018922193


### Finding Array Properties and Performing Operations


##TASK-1

Write a Python program using NumPy to perform the following:


Marks = 65, 78, 90, 55, 88

**Tasks:**

Create a NumPy array using these marks

Find the average marks

Find the highest marks

Find the lowest marks

In [ ]:
import numpy as np

# Create a NumPy array
marks = np.array([65, 78, 90, 55, 88])

# Display the array
print("Marks:", marks)

# Find the average marks
print("Average Marks:", np.mean(marks))

# Find the highest marks
print("Highest Marks:", np.max(marks))

# Find the lowest marks
print("Lowest Marks:", np.min(marks))

##TASK-2

1. Create a NumPy array from 1 to 20 using an inbuilt function

In [ ]:
import numpy as np

# Create an array from 1 to 20
arr = np.arange(1, 21)

print("NumPy Array:")
print(arr)

NumPy Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


2. Create an array of all zeros with 10 elements and convert it into a matrix


In [ ]:
import numpy as np

# Create an array of 10 zeros
arr = np.zeros(10)

# Convert into a 2 × 5 matrix
matrix = arr.reshape(2, 5)

print("Zero Array:")
print(arr)

print("\nMatrix:")
print(matrix)

Zero Array:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Matrix:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


3. Create an array containing even numbers from 2 to 20

In [ ]:
import numpy as np

# Even numbers from 2 to 20
arr = np.arange(2, 21, 2)

print("Even Numbers:")
print(arr)

Even Numbers:
[ 2  4  6  8 10 12 14 16 18 20]


4. Create an array and find its dimensions, shape, size, data type, and multiply every element by 2


In [ ]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Array:")
print(arr)

# Properties
print("\nDimensions:", arr.ndim)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data Type:", arr.dtype)

# Multiply every element by 2
print("\nArray after Multiplication:")
print(arr * 2)

Array:
[[1 2 3]
 [4 5 6]]

Dimensions: 2
Shape: (2, 3)
Size: 6
Data Type: int64

Array after Multiplication:
[[ 2  4  6]
 [ 8 10 12]]


5. Create a 1D array and find Sum, Mean, Maximum and Minimum

In [ ]:
import numpy as np

# Create a 1D array
arr = np.array([10, 20, 30, 40, 50])

print("Array:")
print(arr)

# Aggregate functions
print("\nSum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))

Array:
[10 20 30 40 50]

Sum: 150
Mean: 30.0
Maximum: 50
Minimum: 10


In [ ]:
#MORNING TASK
#1
import numpy as np
Array1 = np.arange(1,21)
print("====Solution-1====")
print(Array1)

#2
Array2 = np.zeros(10)
print("====Solution-2====")
print(Array2)
print(np.shape(Array2))
print(Array2.reshape(5,2))

#3
Array3 = np.arange(2,21,2)
print("====Solution-3====")
print(Array3)

#4
Array4 = np.array([[1,3,2,4],[2,3,4,5]])
print("====Solution-4====")
print(Array4)
print(np.shape(Array4))
print(Array4.size)
print(Array4.dtype)
print(Array4 *2)

#5
Array5 = np.eye(4)
print("====Solution-5=====")
print(np.sum(Array5))
print(np.mean(Array5))
print(np.min(Array5))
print(np.max(Array5))
print(np.std(Array5))

====Solution-1====
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
====Solution-2====
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(10,)
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
====Solution-3====
[ 2  4  6  8 10 12 14 16 18 20]
====Solution-4====
[[1 3 2 4]
 [2 3 4 5]]
(2, 4)
8
int64
[[ 2  6  4  8]
 [ 4  6  8 10]]
====Solution-5=====
4.0
0.25
0.0
1.0
0.4330127018922193
