# Task-01: Building a Neural Network using TensorFlow & Keras

## Objective

The objective of this task is to build a simple Artificial Neural Network (ANN) using TensorFlow and Keras to predict whether a customer will purchase a product based on their age and annual income.

This task demonstrates the complete deep learning workflow, including data preparation, model building, training, evaluation, and prediction.

## Problem Statement

A company wants to identify whether a customer is likely to purchase a product based on customer information such as Age and Annual Income.

By training a neural network on historical customer data, the model learns patterns that help predict whether a new customer is likely to make a purchase.

## About the Dataset

This example uses a manually created dataset for learning purposes.

### Input Features

- Age (in years)
- Annual Income (in USD)

### Output

- Purchase Status
  - 0 → Will Not Purchase
  - 1 → Will Purchase

## Real-Life Applications

- E-commerce Product Recommendation
- Customer Purchase Prediction
- Digital Marketing Campaigns
- Customer Relationship Management (CRM)
- Targeted Advertising
- Sales Forecasting

## Workflow

Customer Data

↓

Data Preprocessing

↓

Build Neural Network

↓

Train the Model

↓

Evaluate Performance

↓

Predict Customer Purchase

## Expected Outcome

The trained neural network predicts whether a new customer is likely to purchase a product based on the provided input features, helping businesses make better marketing and sales decisions.

In [ ]:
# ==========================================
# Building a Neural Network using TensorFlow/Keras
# Example: Predict Product Purchase
# ==========================================

# Step 1: Import Libraries
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np
import pandas as pd

# ------------------------------------------
# Step 2: Create Dataset
# ------------------------------------------

data = {
    "Age":[22,25,28,30,35,40,45,50,55,60],
    "Monthly_Income":[25000,30000,35000,45000,50000,60000,70000,80000,90000,100000],
    "Purchased":[0,0,0,1,1,1,1,1,1,1]
}

df = pd.DataFrame(data)

print("Dataset")
print("-----------------------")
print(df)

# ------------------------------------------
# Step 3: Split Features and Target
# ------------------------------------------

X = df[["Age","Monthly_Income"]].values

y = df["Purchased"].values

# ------------------------------------------
# Step 4: Build Neural Network
# ------------------------------------------

model = Sequential([
    Dense(8, activation='relu', input_shape=(2,)),   # Hidden Layer 1
    Dense(4, activation='relu'),                     # Hidden Layer 2
    Dense(1, activation='sigmoid')                   # Output Layer
])

# ------------------------------------------
# Step 5: Compile the Model
# ------------------------------------------

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# ------------------------------------------
# Step 6: Train the Model
# ------------------------------------------

print("\nTraining Started...\n")

history = model.fit(
    X,
    y,
    epochs=100,
    verbose=1
)

print("\nTraining Completed!")

# ------------------------------------------
# Step 7: Evaluate the Model
# ------------------------------------------

loss, accuracy = model.evaluate(X, y, verbose=0)

print("\nModel Evaluation")
print("-----------------------")
print("Loss     :", round(loss,4))
print("Accuracy :", round(accuracy*100,2), "%")

# ------------------------------------------
# Step 8: Make Predictions
# ------------------------------------------

print("\nPredictions")
print("-----------------------")

test_data = np.array([
    [27,38000],
    [33,52000],
    [48,85000],
    [24,28000]
])

predictions = model.predict(test_data)

for customer, pred in zip(test_data, predictions):

    probability = pred[0]

    if probability >= 0.5:
        result = "Will Purchase"
    else:
        result = "Will Not Purchase"

    print(f"Age: {customer[0]}, Income: ₹{customer[1]} -> Probability: {probability:.4f} -> Prediction: {result}")

# ------------------------------------------
# Step 9: Model Summary
# ------------------------------------------

print("\nModel Summary")
print("-----------------------")
model.summary()

# ------------------------------------------
# Step 10: Display Weights and Biases
# ------------------------------------------

print("\nModel Weights and Biases")
print("-----------------------")

for i, layer in enumerate(model.layers):

    weights, biases = layer.get_weights()

    print(f"\nLayer {i+1}")

    print("Weights:")
    print(weights)

    print("Biases:")
    print(biases)

# ------------------------------------------
# Step 11: Predict for a New Customer
# ------------------------------------------

age = 38
income = 65000

prediction = model.predict(np.array([[age, income]]))

print("\nNew Customer Prediction")
print("-----------------------")
print("Age :", age)
print("Monthly Income :", income)
print("Probability :", prediction[0][0])

if prediction[0][0] >= 0.5:
    print("Final Prediction : CUSTOMER WILL PURCHASE")
else:
    print("Final Prediction : CUSTOMER WILL NOT PURCHASE")

Dataset
-----------------------
   Age  Monthly_Income  Purchased
0   22           25000          0
1   25           30000          0
2   28           35000          0
3   30           45000          1
4   35           50000          1
5   40           60000          1
6   45           70000          1
7   50           80000          1
8   55           90000          1
9   60          100000          1

Training Started...



/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.7000 - loss: 6352.1343
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 225ms/step - accuracy: 0.7000 - loss: 6311.0205
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - accuracy: 0.7000 - loss: 6270.0718
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step - accuracy: 0.7000 - loss: 6229.2910
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.7000 - loss: 6188.6807
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.7000 - loss: 6148.2422
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.7000 - loss: 6107.9805
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - accuracy: 0.7000 - loss: 6067.8960
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.7000 - loss: 6027.9917
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - accuracy: 0.7000 - loss: 5988.2695
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.7000 - loss: 5948.7319
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 8)              │            24 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 4)              │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 197 (792.00 B)

 Trainable params: 65 (260.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 132 (532.00 B)


Model Weights and Biases
-----------------------

Layer 1
Weights:
[[ 0.52401143 -0.21609032  0.04414511 -0.00268948 -0.3866616   0.3887203
  -0.39425296 -0.16667193]
 [ 0.4905135  -0.2815296  -0.11818075 -0.09037286 -0.66853595  0.11084405
  -0.08711308 -0.5717103 ]]
Biases:
[-0.09320847  0.          0.          0.          0.         -0.0769951
  0.          0.        ]

Layer 2
Weights:
[[-0.1049785   0.42297944 -0.02105283  0.2694965 ]
 [-0.632853   -0.3513294   0.69360715 -0.69120276]
 [-0.56483215 -0.36539647 -0.07174909 -0.6767676 ]
 [ 0.04047275 -0.4509438   0.24368244 -0.14943957]
 [ 0.12341726 -0.00739747  0.44028944 -0.60901976]
 [ 0.06109828  0.28305227  0.54574215  0.37665924]
 [ 0.6968042  -0.20863819 -0.48728213  0.23778611]
 [ 0.27650017  0.44670135  0.26961523 -0.585973  ]]
Biases:
[ 0.         -0.09848215  0.10201592 -0.09843081]

Layer 3
Weights:
[[-0.18730885]
 [ 0.99762505]
 [-1.0405053 ]
 [ 0.95038855]]
Biases:
[-0.09999919]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step
